### ISSUE TITLE
Foods are very close to each other when they  come up on the screen.

### ISSUE THREAD

**Issue by anastasia-horbachevska** [awlzac/greenwall#2]
**Description:** 

Due to this defect in the game, the player can't take certain foods or loses when one of the products is Ketchup.

**Steps to reproduce:**
1. Open the game.
2. Start to play in the game.

**Actual result:**

Foods appear on the screen very close together.
![image](https://user-images.githubusercontent.com/60118831/74837637-f9a48380-5332-11ea-8367-95d955c3f974.png)
![image](https://user-images.githubusercontent.com/60118831/74837659-04f7af00-5333-11ea-8026-bb8ebd37f31d.png)

**Expected result:**

Foods should be at a certain distance so that the gamer can take the food he needs.

**Additional info:**

Tested on devices: Mi Note 7

**Comment by awlzac** [comment]
This is expected behavior; in this style of old-school arcade game, trick/trap situations where the player must quickly decide between less points and the risk of losing a life, are intended to occur.
