### ISSUE TITLE
The principle of mixing food and its disappearance from the wall

### ISSUE THREAD

**Issue by anastasia-horbachevska** [awlzac/greenwall#4]
**Description:**

 There is no description in the game of how products mix together to disappear.
 Foods begin to mix and disappear from level 3.

**Steps to reproduce:**
1. Open the game.
2. Play more than three levels.

**Actual result:**

The foods that the player threw into the wall, it is not known how to mix with each other.

**Expected result:**

Foods that the player throws into the wall mix with each other according to the principle that the player knows.

**Additional info:**

Tested on devices: Mi Note 7

**Comment by awlzac** [comment]
This is expected behavior; the intent is for the player to discover the combos through play.
